//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDHPRIMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnose
    {
        public long DiagnosisNo { get; set; }
        public Nullable<long> HospitalNo { get; set; }
        public Nullable<System.DateTime> DateAdmitted { get; set; }
        public Nullable<System.DateTime> DateDischarge { get; set; }
        public string AdmissionType { get; set; }
        public string Physician { get; set; }
        public string AdmissionDiagnosis { get; set; }
        public string PrincipalDiagnosis { get; set; }
        public string PrinProce { get; set; }
        public string Disposition { get; set; }
        public string Results { get; set; }
    }
}
