//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDHPRIMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public long PrescriptID { get; set; }
        public Nullable<long> DiagnosisID { get; set; }
        public Nullable<long> HospitalNo { get; set; }
        public string Prescription { get; set; }
        public Nullable<System.DateTime> DatePrescribed { get; set; }
    }
}
