//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDHPRIMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public long HospitalNo { get; set; }
        public string Firstname { get; set; }
        public string Midname { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Age { get; set; }
        public string Birthplace { get; set; }
        public string City { get; set; }
        public string Barangay { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }
        public string Father { get; set; }
        public string Mother { get; set; }
    }
}
